/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/EFFHsSSBJTaF6RGO/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#5e6063"]} />
      <group {...props} dispose={null}>
        <group name="cap">
          <mesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials.body}
            castShadow
            receiveShadow
            position={[1.05, -57, -116.85]}
            scale={4.78}
          />
          <mesh
            name="tag"
            geometry={nodes.tag.geometry}
            material={materials.tag}
            castShadow
            receiveShadow
            position={[12.48, -149.8, 229.84]}
            rotation={[0, 1.55, 0]}
            scale={[1.68, 0.41, 1.68]}
          />
          <mesh
            name="bill"
            geometry={nodes.bill.geometry}
            material={materials.bill}
            castShadow
            receiveShadow
            position={[0, -157.78, -121.67]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[4.36, 0.11, 4.41]}
          />
          <mesh
            name="centerupball"
            geometry={nodes.centerupball.geometry}
            material={materials.tip}
            castShadow
            receiveShadow
            position={[2.73, 164.24, -116.95]}
            scale={[0.5, 0.74, 0.5]}
          />
          <group name="contorns" position={[0, -155.51, -116.79]}>
            <mesh
              name="contornbase"
              geometry={nodes.contornbase.geometry}
              material={materials.body}
              castShadow
              receiveShadow
              position={[0, 2.86, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[4.36, 0.11, 4.41]}
            />
            <mesh
              name="interiorcontorn"
              geometry={nodes.interiorcontorn.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, -3.18, 3.58]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[4.13, 0.1, 4.17]}
            />
          </group>
          <group name="billdetails" position={[0, -151.67, 153.18]}>
            <mesh
              name="billdetail5"
              geometry={nodes.billdetail5.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, 0, -184.56]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[4.01, 0.04, 4.06]}
            />
            <mesh
              name="billdetail4"
              geometry={nodes.billdetail4.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, 0, -184.56]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[3.79, 0.03, 3.83]}
            />
            <mesh
              name="billdetail3"
              geometry={nodes.billdetail3.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, 0, -184.56]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[3.5, 0.03, 3.45]}
            />
            <mesh
              name="billdetail2"
              geometry={nodes.billdetail2.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, 0, -184.56]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[3.14, 0.03, 3.17]}
            />
            <mesh
              name="billdetail1"
              geometry={nodes.billdetail1.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, 0, -184.56]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[2.72, 0.02, 2.74]}
            />
          </group>
          <group name="eyelets" position={[-0.3, 137.99, -116.57]}>
            <mesh
              name="eyelet2_right"
              geometry={nodes.eyelet2_right.geometry}
              material={materials.tip}
              castShadow
              receiveShadow
              position={[-81.46, -0.58, 77.68]}
              rotation={[-1.29, -0.33, -0.1]}
              scale={[0.35, 0.35, 0.58]}
            />
            <mesh
              name="eyelet2_left"
              geometry={nodes.eyelet2_left.geometry}
              material={materials.tip}
              castShadow
              receiveShadow
              position={[87.1, -2.51, 87.36]}
              rotation={[-1.24, 0.32, -0.1]}
              scale={[0.35, 0.35, 0.58]}
            />
            <group
              name="eyelet1_right"
              position={[-84.88, 1.18, -85.6]}
              scale={[-1.1, 1, 1]}
            >
              <mesh
                name="eyelet1_right1"
                geometry={nodes.eyelet1_right1.geometry}
                material={materials.tip}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[-1.93, 0.29, 0.17]}
                scale={[0.35, 0.35, 0.58]}
              />
            </group>
            <group name="eyelet1_left" position={[84.26, 1.18, -85.6]}>
              <mesh
                name="eyelet1_left1"
                geometry={nodes.eyelet1_left1.geometry}
                material={materials.tip}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[-1.93, 0.29, 0.17]}
                scale={[0.35, 0.35, 0.58]}
              />
            </group>
          </group>
        </group>
        <directionalLight
          name="Directional Light Main"
          intensity={0.6}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-412.853}
          shadow-camera-right={412.853}
          shadow-camera-top={412.853}
          shadow-camera-bottom={-412.853}
          position={[-549.14, 336.02, 736]}
        />
        <OrthographicCamera
          name="1"
          zoom={0.5}
          makeDefault={true}
          far={100000}
          near={-100000}
          position={[0, 0, 1000]}
          scale={1}
        />
      </group>
    </>
  );
}
