/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function HoodieModel({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/BwpybOEor7UmZ3ub/scene.splinecode"
  );

  return (
    <>
      <color attach="background" args={["#979797"]} />
      <group {...props} dispose={null}>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={1}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1000}
          shadow-camera-right={1000}
          shadow-camera-top={1000}
          shadow-camera-bottom={-1000}
          position={[0, 803.54, 896.62]}
        />
        <group name="hoodie">
          <mesh
            name="base"
            geometry={nodes.base.geometry}
            material={materials["hoodie body"]}
            castShadow
            receiveShadow
            position={[7.92, 54.86, -0.29]}
            rotation={[0, -0.03, 0]}
            scale={1}
          />
          <group name="laces" position={[-2.24, 110.43, 94.28]}>
            <mesh
              name="Torus 2"
              geometry={nodes["Torus 2"].geometry}
              material={materials["hoodie body"]}
              castShadow
              receiveShadow
              position={[33.95, 88.25, -30.52]}
              rotation={[0.14, 0.24, 0.01]}
              scale={[-0.59, 0.59, 0.59]}
            />
            <mesh
              name="Torus"
              geometry={nodes.Torus.geometry}
              material={materials["hoodie body"]}
              castShadow
              receiveShadow
              position={[-30.93, 88.37, -33.51]}
              rotation={[0.16, -0.24, 0.01]}
              scale={0.59}
            />
            <group
              name="left"
              position={[29.62, 6.46, -2.17]}
              rotation={[0.02, 0, 0]}
              scale={[1.07, 0.93, 1]}
            >
              <mesh
                name="Cylinder 3"
                geometry={nodes["Cylinder 3"].geometry}
                material={materials["Cylinder 3 Material"]}
                castShadow
                receiveShadow
                position={[-0.73, -92.78, 20.2]}
                rotation={[0, -0.03, 0]}
                scale={[0.17, 0.19, 0.17]}
              />
              <mesh
                name="Subdiv 4"
                geometry={nodes["Subdiv 4"].geometry}
                material={materials["hoodie strings"]}
                castShadow
                receiveShadow
                position={[2.8, 17.17, 5.2]}
                rotation={[-0.26, -0.03, -0.01]}
                scale={[-0.68, 1.69, 0.68]}
              />
            </group>
            <group name="right" position={[-29.6, -0.23, -1.41]}>
              <mesh
                name="Cylinder 2"
                geometry={nodes["Cylinder 2"].geometry}
                material={materials["Cylinder 2 Material"]}
                castShadow
                receiveShadow
                position={[-0.25, -92.55, 21]}
                rotation={[0, -0.03, 0]}
                scale={[0.17, 0.19, 0.17]}
              />
              <mesh
                name="Cylinder"
                geometry={nodes.Cylinder.geometry}
                material={materials["hoodie strings"]}
                castShadow
                receiveShadow
                position={[-2.67, 17.41, 5.76]}
                rotation={[-0.26, -0.03, -0.01]}
                scale={[0.68, 1.69, 0.68]}
              />
            </group>
          </group>
        </group>
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={0.4}
          far={100000}
          near={-100000}
          position={[22.65, 441.84, 1372.17]}
          rotation={[-0.19, -0.04, -0.01]}
          scale={1}
        />
      </group>
    </>
  );
}
